// Generated by https://quicktype.io

// export interface PokemonListResponse {
//   ref:  Ref;
//   prop: string;
// }

// export interface Ref {
//   "0h0e2a1pTOw": The0H0E2A1PTOw;
// }

export interface PokemonListResponse {
  count:    number;
  next:     string;
  previous: string;
  results:  BasicPokemonInfo[];
}

export interface BasicPokemonInfo {
  name: string;
  url:  string;
}
